spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chime
    username: chime_user
    password: chime_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  data:
    redis:
      host: localhost
      port: 6379
      password: redispass

logging:
  level:
    com.ankitha: DEBUG
    org.springframework.security: DEBUG